Update validate-IaC-deploymentarch-controls.yaml

diff --git a/.github/workflows/validate-IaC-deploymentarch-controls.yaml b/.github/workflows/validate-IaC-deploymentarch-controls.yaml
--- a/.github/workflows/validate-IaC-deploymentarch-controls.yaml
+++ b/.github/workflows/validate-IaC-deploymentarch-controls.yaml
@@ -135,9 +135,11 @@ jobs:
           echo "Current working directory:"
           pwd
           echo "Check for terraform_compliance_report.md from current dir:"
-          find . -name "terraform_compliance_report.md" -print
+          find . -name "*.md" -print
           echo "Full report path (if exists):"
           find . -type f -name "terraform_compliance_report.md" -exec realpath {} \; || echo "Report not found"
+          echo "Full report path (if exists):"
+          find . -type f -name "IaC_control_analysis.md" -exec realpath {} \; || echo "Report not found"
           git add compliance-reports/IaC_control_analysis.md
           git commit -m "Update IaC controls compliance report" || echo "No changes to commit"
           # Push and ignore error if branch was updated concurrently
