Update validate-IaC-deploymentarch-controls.yaml

diff --git a/.github/workflows/validate-IaC-deploymentarch-controls.yaml b/.github/workflows/validate-IaC-deploymentarch-controls.yaml
--- a/.github/workflows/validate-IaC-deploymentarch-controls.yaml
+++ b/.github/workflows/validate-IaC-deploymentarch-controls.yaml
@@ -106,21 +106,21 @@ jobs:
 
       - name: Debug – List report files
         if: always()
-        run: ls -l aac-direct-debit-update/compliance-reports || echo "Directory not found"
+        run: ls -lR compliance-reports || echo "Directory not found"
 
       - name: Upload report artifacts
         if: always()
         uses: actions/upload-artifact@v4
         with:
           name: policy-evaluation-report-controls
-          path: aac-direct-debit-update/compliance-reports/IaC_control_analysis.md
+          path: compliance-reports/IaC_control_analysis.md
 
       - name: Commit and push report
         if: always()
         run: |
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
-          git add aac-direct-debit-update/compliance-reports/IaC_control_analysis.md
+          git add compliance-reports/IaC_control_analysis.md
           git commit -m "Update IaC controls compliance report" || echo "No changes to commit"
           git push
         env:
