Update validate-architecture-policies.yaml

diff --git a/.github/workflows/validate-architecture-policies.yaml b/.github/workflows/validate-architecture-policies.yaml
--- a/.github/workflows/validate-architecture-policies.yaml
+++ b/.github/workflows/validate-architecture-policies.yaml
@@ -101,11 +101,11 @@ jobs:
           echo "Current working directory:"
           pwd
 
-           echo "Check for policy_evaluation_report.md from current dir:"
-           find . -name "policy_evaluation_report.md" -print
+           echo "Check for Architecture_Policy_Compliance_Report.md from current dir:"
+           find . -name "Architecture_Policy_Compliance_Report.md" -print
 
           echo "Full report path (if exists):"
-          find . -type f -name "policy_evaluation_report.md" -exec realpath {} \; || echo "Report not found"
+          find . -type f -name "Architecture_Policy_Compliance_Report.md" -exec realpath {} \; || echo "Report not found"
 
           echo "Directory tree around compliance-reports:"
           tree -L 2 || ls -R
@@ -120,14 +120,25 @@ jobs:
         uses: actions/upload-artifact@v4
         with:
           name: policy-evaluation-report
-          path: compliance-reports/policy_evaluation_report.md
+          path: compliance-reports/Architecture_Policy_Compliance_Report.md
 
       - name: Commit and push report
         if: always()
         run: |
           git config user.name "github-actions[bot]"  # Set Git username
           git config user.email "github-actions[bot]@users.noreply.github.com"  # Set Git email
-          git add compliance-reports/policy_evaluation_report.md  # Stage report file
+         
+          TIMESTAMP=$(date +"%d%m%y-%H%M%S")
+          
+          echo "Full report paths (if exist):"
+          find . -type f -name "Architecture_Policy_Compliance_Report.md" -exec realpath {} \; || echo "terraform_compliance_report.md not found"
+          
+          # Stage  report exist
+          if [ -f compliance-reports/Architecture_Policy_Compliance_Report.md ]; then
+            mv compliance-reports/Architecture_Policy_Compliance_Report.md compliance-reports/Architecture_Policy_Compliance_Report_${TIMESTAMP}.md
+            git add compliance-reports/Architecture_Policy_Compliance_Report_${TIMESTAMP}.md
+          fi
+         
           git commit -m "Update Architecture vs policy analysis report" || echo "No changes to commit"  # Commit or skip if no changes
           git push origin ${{ github.head_ref }} || echo "Push failed (possibly due to concurrent updates)"
         env:
